Add a Failure Metric Increment Event based on failed CRD validation
sky-uk/cassandra-operator pull request #233
Opened 2020-10-30 15:51 UTC by Bez625

When an invalid change is made to the cassandra resource there is currently no visibility as to whether the change has successfully passed validation or not. 

This PR adds an IncrementValidationFailures Event that will increment a prometheus counter for `cassandra_failed_validation_count` on the prometheus metrics endpoint. 

IncrementValidationFailures is emitted by the reconciler when Cassandra cluster validation has failed at the point an InvalidChange event is currently recorded by the Operator.

2020-11-02 18:34 UTC, sebbonnet requested changes
Thanks for the contribution Chris!

Could you add some additional checks in the e2e tests so we can see the new metrics in actions? 
You'll find that we already check `InvalidChangeEvent` are reported in `invalid_modification_test`, so it would be good to ensure the new metric is reported there too.
I also think we should ensure the counter is initialised to `0` and so you could also add a check in the `creation_test` under `should report metrics for all clusters`.

If you're planning on releasing this change, then we'd also need a line in the CHANGELOG

2020-11-02 18:34 UTC, sebbonnet commented on cassandra-operator/pkg/operator/reconciler.go
> +	r.metricsReporter.InitialiseFailedValidationMetric(desiredCassandra.Name, desiredCassandra.Namespace)
should we move this method call to `determineChangesForCassandraDefinition` instead just before the Cassandra validation is invoked?

2020-11-02 18:34 UTC, sebbonnet commented on cassandra-operator/pkg/metrics/prometheus.go
> +type PrometheusMetricsInterface interface {
Maybe call this `MetricsReporter` instead, so we don't have either Prometheus (the implementation) nor Interface in the name?

2020-11-02 18:34 UTC, sebbonnet commented on cassandra-operator/pkg/metrics/prometheus.go
> +	IncrementFailedValidationMetric(clusterName string, clusterNamespace string)
Should we use `*v1alpha1.Cassandra` as argument instead, to avoid mixing up the 2 args which look similar?
We could potentially expose the other functions (e.g. DeleteMetrics, UpdateMetrics, ...) in the interface and streamline them, so they all take a `*v1alpha1.Cassandra` as argument.

2020-11-02 18:34 UTC, sebbonnet commented on cassandra-operator/pkg/operator/controller_test.go
> +}
newline missing

2020-11-03 07:44 UTC, Bez625 commented on cassandra-operator/pkg/metrics/prometheus.go
> +type PrometheusMetricsInterface interface {
I have changed this to `ClusterMetricsReporter` as `MetricsReporter` failed the lint check

2020-11-03 07:57 UTC, Bez625 commented on cassandra-operator/pkg/operator/controller_test.go
> +}
I have added this, but it didn't show up in lint and I can't see any references to it being a particular go coding style. 

Is this a coding convention that was agreed to as part of the operator? I'm wondering if we can add build time tests to enforce this going forward.

2020-11-03 08:05 UTC, Bez625 commented on cassandra-operator/pkg/metrics/prometheus.go
> +	IncrementFailedValidationMetric(clusterName string, clusterNamespace string)
I agree with this and I have changed for the new functions. I looked at updating the existing functions and I was a bit apprehensive to do so as part of this PR as it is quite a big change.

Let me know if you feel it should be done as part of this PR and I'll update them

2020-11-03 10:21 UTC, sebbonnet commented on cassandra-operator/pkg/metrics/prometheus.go
> +	IncrementFailedValidationMetric(clusterName string, clusterNamespace string)
I would rather do it now that we've introduced the interface. It's a low risk change and will give you the opportunity to view a bit more of the code  :)

2020-11-03 10:26 UTC, sebbonnet commented on cassandra-operator/pkg/operator/controller_test.go
> +}
it's not a code convention, but more like a best practice as some unix tools would not cope well without it (wc is one example I can think of). github flags the missing new line in the changeset.

2020-11-03 10:32 UTC, sebbonnet reviewed
Just a couple more points to address.
Let's use the ClusterMetricsReporter interface. It's a low risk change and will give you the opportunity to view a bit more of the code :)

2020-11-03 10:32 UTC, sebbonnet commented on CHANGELOG.md
> +## 0.82.2-alpha
We should increment the minor version for new feature. The patch version should be incremented for bug fixes.
So here it should be 0.83.0-alpha

2020-11-03 10:32 UTC, sebbonnet commented on cassandra-operator/pkg/metrics/prometheus.go
> +func (m *PrometheusMetrics) IncrementFailedValidationMetric(desiredCassandra *v1alpha1.Cassandra) {
`desiredCassandra` can we call that simply `cassandra`, the "desired" part is only used when we reconcile the "desired" state based on the "actual" state

2020-11-03 10:32 UTC, sebbonnet commented on cassandra-operator/pkg/metrics/prometheus.go
> +func (m *PrometheusMetrics) InitialiseFailedValidationMetric(desiredCassandra *v1alpha1.Cassandra) {
same comment as above

2020-11-03 10:32 UTC, sebbonnet commented on cassandra-operator/pkg/operator/event/receiver.go
> +func NewEventReceiver(clusterAccessor cluster.Accessor, metricsReporter *metrics.PrometheusMetrics, eventRecorder record.EventRecorder) Receiver {
I would use the interface here once we expose the other functions

2020-11-03 12:31 UTC, sebbonnet approved these changes

2020-11-03 12:40 UTC, merged