Add configurable snapshot and snapshot-cleanup job resources
sky-uk/cassandra-operator pull request #240
Opened 2020-12-10 16:34 UTC by Bez625

required by https://github.com/sky-uk/cassandra-operator/issues/238

* Add resources for Snapshot and Snapshot.RetentionPolicy within the Cassandra Resource Spec
* Apply resources to snapshot job and snapshot-cleanup job when those are created or modified.
* If neither are supplied we set the requirements to the previous default values (limits: 50Mi, requests: 100m, 50Mi).
* Testing for the above cases.

2020-12-11 18:26 UTC, sebbonnet requested changes
I don't think the reconciliation logic is going to work for snapshots when you change the resource requirements as the defaults are not applied to both desired and actual cassandra and there is no logic to reconcile the snapshot resources.
Also remember to add that change in the changelog - assuming you're going to release this :)

2020-12-11 18:26 UTC, sebbonnet commented on cassandra-operator/pkg/cluster/cluster.go
> +func generateResources(clusterResources v1.ResourceRequirements) v1.ResourceRequirements {
Default values for fields we expose in the Cassandra definition should all be set in the same place (via `v1alpha1helpers.SetDefaultsForCassandra`).
This is so the reconciler can compare both the current and desired cassandra based on the same default values. 
I think if you added a test that creates a Snapshot without resource requirements the reconciler would always find that the desired Cassandra is always different than the actual one as you only apply default to the actual one.
Also keeping the code in the same place would make it easier if we ever decide to write a mutating validation webhook that would set the defaults using that single entry point.

2020-12-11 18:26 UTC, sebbonnet commented on cassandra-operator/pkg/cluster/cluster.go
> +func generateResources(clusterResources v1.ResourceRequirements) v1.ResourceRequirements {
Conversely the reconciler should apply the changes if you change the values of the Snapshot resource requirements.
I can't see any change in the snapshot state reconciliation `snapshotstate.go`, so I don't think this would work.
Do we have a test for that?

2020-12-11 18:26 UTC, sebbonnet commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
same comment about api conventions

2020-12-14 07:05 UTC, Bez625 commented on cassandra-operator/kubernetes-resources/cassandra-operator-deployment.yml
> +        imagePullPolicy: Always # For dev purposes as kind caches images and will not pull images with same commit tag
This is something both @chuckydev and I found during development. We were trying to iterate on code locally and run tests using kind. As we were working on local changes the git tag (and therefore image tag) wasn't changing when the code was. 

I believe as per [the notes here](https://kubernetes.io/docs/concepts/configuration/overview/#container-images) that it will still use caches for the image layers, so it is still fairly efficient to use this strategy. I'm happy to discuss this though as it is quite opinionated and potentially changes existing dev patterns.

2020-12-14 08:58 UTC, Bez625 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
So i've taken a look at this and im a little confused. If I look at the Container struct within the [kubernetes api](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2258) they do NOT seem to be following this convention.

From what I can see `Resources` is both optional and a type (struct) that does not have a built in value of nil. Am I missing something here?

2020-12-14 09:01 UTC, Bez625 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
The reason I'm questioning this is that it's kind of annoying as it means we can have a valid nil value for the resources defined on the cassandra snapshot spec, but then have to provide _something_ to the Container resources value.

2020-12-14 09:35 UTC, sebbonnet commented on cassandra-operator/kubernetes-resources/cassandra-operator-deployment.yml
> +        imagePullPolicy: Always # For dev purposes as kind caches images and will not pull images with same commit tag
if you need to make a change you can always do another commit and rebuild your image or tag your image with latest.
I think using the default policy for pulling images promotes the use of immutable images which is a good thing to have

2020-12-14 09:40 UTC, sebbonnet commented on cassandra-operator/kubernetes-resources/cassandra-operator-deployment.yml
> +        imagePullPolicy: Always # For dev purposes as kind caches images and will not pull images with same commit tag
I think it's wrong to change this just to accommodate your testing

2020-12-14 11:17 UTC, sebbonnet commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
> So i've taken a look at this and im a little confused. If I look at the Container struct within the kubernetes api they do NOT seem to be following this convention.

:laughing: well it looks like they don't follow their own convention

> The reason I'm questioning this is that it's kind of annoying as it means we can have a valid nil value for the resources defined on the cassandra snapshot spec

You cannot have `nil` value with a struct - it needs to be a pointer.
Without using pointers you won't be able to tell whether the user request a cpu with value "0" or no cpu at all and therefore you don't know when you can apply the defaults.
Try this
```
			var noValue resource.Quantity
			zeroValue := resource.MustParse("0")
			Expect(noValue.Value()).To(Equal(zeroValue.Value()))

			var optionalValue *resource.Quantity
			// panics
			Expect(optionalValue.Value()).To(Equal(zeroValue.Value()))
```

2020-12-29 09:36 UTC, alangibson01 requested changes

2020-12-29 09:36 UTC, alangibson01 commented on cassandra-operator/Makefile
> +
This feels a little dangerous to me, especially the `delete all` line. All it takes is a badly-defined env var and damaging things could happen. It'd be better to limit just to a certain set of fixed namespaces if possible.

2020-12-29 09:36 UTC, alangibson01 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/helpers/cassandra_test.go
> +		})
I don't think ordering of properties in struct declarations is relevant. You can remove this test.

2020-12-29 09:36 UTC, alangibson01 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/helpers/cassandra_test.go
> +		})
As above.

2020-12-29 09:36 UTC, alangibson01 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
Is this conversation out-of-date now that resources are mandatory?

2020-12-29 09:36 UTC, alangibson01 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
As above.

2020-12-29 09:48 UTC, Bez625 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
Yeah I think so. We came full circle

2020-12-29 09:49 UTC, Bez625 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go
> +	Resources coreV1.ResourceRequirements `json:"resources"`
Yep outdated following the mandatory decision

2020-12-29 09:51 UTC, Bez625 commented on cassandra-operator/Makefile
> +
Fair enough. Given this is a util method and not used by the travis/jenkins pipelines I will hardcode the namespace to the test namespace.

2020-12-29 10:32 UTC, sebbonnet reviewed
some more comments on how to improve the tests

2020-12-29 10:32 UTC, sebbonnet commented on cassandra-operator/test/e2e/parallel/modification/external_modification_test.go
> +			TheSnapshotCronJobIsEdited(Namespace, clusterName, editedSnapshotJob)
I think we should avoid calling functions from the production code such as `aCluster.CreateSnapshotJob()`
Can we do something similar to `TheClusterPodResourcesSpecAreChangedTo` where we mutate a copy of the server representation of the object?

2020-12-29 10:32 UTC, sebbonnet commented on cassandra-operator/test/e2e/parallel/modification/external_modification_test.go
> +			TheSnapshotCleanupCronJobIsEdited(Namespace, clusterName, editedSnapshotCleanupJob)
same as above

2020-12-29 10:32 UTC, sebbonnet commented on cassandra-operator/pkg/cluster/cluster_test.go
> +	It("should create a cronjob with the specified memory and cpu resources", func() {
Can we have a similar test for the snapshot cleanup job?

2020-12-29 12:41 UTC, sebbonnet commented on cassandra-operator/pkg/cluster/cluster.go
> +func generateResources(clusterResources v1.ResourceRequirements) v1.ResourceRequirements {
this is fixed in more recent commits

2020-12-29 12:43 UTC, sebbonnet approved these changes
lgtm

2020-12-29 12:43 UTC, sebbonnet commented on cassandra-operator/test/e2e/parallel/modification/external_modification_test.go
> +			TheSnapshotCronJobIsEdited(Namespace, clusterName, editedSnapshotJob)
fixed in a more recent commit

2020-12-29 13:22 UTC, alangibson01 approved these changes

2020-12-29 13:22 UTC, merged