Explicitly define Sidecar Resources
sky-uk/cassandra-operator pull request #249
Opened 2021-01-27 14:54 UTC by chuckydev

Required by #243 

**Currently**

Sidecar resources are currently defined by the pod size and floored to 50Mi and bursting CPU. We would like all resources to be more explicit and part of the cassandra resource itself

**End Approach**

Sidecar ìmage` and `resources` have now been added to their own block in the sky-uk cassandra resource as a Child of `pod`. The same validation as other resources has been included.

```
  pod:
    bootstrapperImage: 
    image:
    readinessProbe:
      timeoutSeconds: 
    resources:
      limits:
        memory: 
      requests:
        cpu: 
        memory: 
    sidecar:
      image: 
      resources:
        requests:
          cpu: 
          memory: 
        limits:
          memory: 
```

This is a **breaking change** as sidecarImage has been moved to `sidecar.image`, resources are mandatory. `sidecar.image` remains defaulted and optional.

A change will also be made to the wiki to describe this change.

I have also added a fix to genereate-all which was currently not working due to a bad path. 
https://github.com/kubernetes/sample-apiserver#when-using-go-111-modules
https://github.com/kubernetes/code-generator/issues/57

2021-01-27 15:47 UTC, Bez625 requested changes

2021-01-27 15:47 UTC, Bez625 commented on cassandra-operator/hack/update-codegen.sh
> +  --output-base ${projectDir}/../../../..
Is it possible to replace the relative path with something more explicit?

2021-01-27 15:47 UTC, Bez625 commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types_test.go
> +			Entry("when pods have different sidecar images", func(pod, _ *Pod) { pod.Sidecar.Image = ptr.String("another image") }),
Are these needed? It looks like they are repeated in the sidecar specific checks below

2021-01-27 15:47 UTC, Bez625 commented on cassandra-operator/pkg/cluster/cluster.go
> +		Resources: *&c.definition.Spec.Pod.Sidecar.Resources,
Should this not be `c.definition.Spec.Pod.Sidecar.Resources` ?

2021-01-27 15:47 UTC, Bez625 commented on cassandra-operator/test/apis/builder.go
> +type SidecarBuilder interface {
Is this used anywhere?

2021-01-27 15:47 UTC, Bez625 commented on cassandra-snapshot/test/e2e/steps.go
> +	renameSnapshot(pods, fmt.Sprintf("%d", newSnapshotName))
Is this to remove the casting? I'm assuming it is just code quality and the format is the same?

2021-01-27 15:47 UTC, Bez625 commented on cassandra-operator/test/e2e/parallel/modification/sidecar_external_modifiation_test.go
> +	It("should eventually return the sidecar container definitions back desired state if the sidecar image is changed", func() {
Is the word "back" in this incorrectly?

2021-01-27 15:51 UTC, chuckydev commented on cassandra-operator/hack/update-codegen.sh
> +  --output-base ${projectDir}/../../../..
Unfortunately not. I know its not great, but there are real limitations with the path being in a `github.com/sky-uk/cassandra-operator` folder. And going from the script dir I think thats the best route. Its also how kubernetes do this in sample-apiserver which is a reference app for code-generator

https://github.com/kubernetes/sample-apiserver#when-using-go-111-modules
kubernetes/code-generator#57

2021-01-27 16:04 UTC, chuckydev commented on cassandra-operator/pkg/apis/cassandra/v1alpha1/types_test.go
> +			Entry("when pods have different sidecar images", func(pod, _ *Pod) { pod.Sidecar.Image = ptr.String("another image") }),
I left them in as they still have a function of prooving that sidecar is involved in Pod equality.

2021-01-28 15:07 UTC, sebbonnet requested changes
lgtm - just a few minor comments to address

2021-01-28 15:07 UTC, sebbonnet commented on cassandra-operator/test/apis/builder.go
> +			coreV1.ResourceCPU:    resource.MustParse("100m"),
we should probably default to bursting (e.g. 0 request)

2021-01-29 10:57 UTC, chuckydev commented on cassandra-operator/test/e2e/parallel/modification/modification_test.go
> +						coreV1.ResourceCPU:    resource.MustParse("100m"),
Ive now asserted the sidecar resources as part of a modification test just to verify.

2021-01-29 10:58 UTC, chuckydev commented on cassandra-operator/test/e2e/parallel/creation/creation_test.go
> +							coreV1.ResourceMemory: resource.MustParse("50Mi"),
Ive now asserted the sidecar resources as part of the happy case creation test

2021-01-29 11:46 UTC, sebbonnet approved these changes

2021-01-29 11:46 UTC, sebbonnet commented on cassandra-operator/hack/update-codegen.sh
> +${codeGenDir}/generate-groups.sh all \
good catch! :)

2021-01-29 11:54 UTC, Bez625 approved these changes

2021-01-29 13:18 UTC, merged

2021-01-29 13:18 UTC, chuckydev commented on cassandra-operator/hack/update-codegen.sh
> +${codeGenDir}/generate-groups.sh all \
Have to put this down to a good eye by @Bez625 :)